export interface SejongAlumniEmploymentData {
  companyName: string;
  companySize: string;
  yearsEstablished: number | null;
  location: string;
  startingSalary: number | null; // 만원 단위
  ojakgyoRank: string;
  graduateEmployment: number;
}

export const SEJONG_ALUMNI_DATA: SejongAlumniEmploymentData[] = [
  { companyName: "삼성전자", companySize: "대기업·계열사·자회사", yearsEstablished: 57, location: "경기", startingSalary: 4051, ojakgyoRank: "C", graduateEmployment: 52 },
  { companyName: "엘지전자", companySize: "대기업·계열사·자회사", yearsEstablished: 24, location: "서울", startingSalary: 4018, ojakgyoRank: "C", graduateEmployment: 14 },
  { companyName: "현대자동차", companySize: "대기업·계열사·자회사", yearsEstablished: 59, location: "서울", startingSalary: 4051, ojakgyoRank: "S", graduateEmployment: 13 },
  { companyName: "삼성에스디에스", companySize: "대기업·계열사·자회사", yearsEstablished: 41, location: "서울", startingSalary: 4018, ojakgyoRank: "C", graduateEmployment: 12 },
  { companyName: "현대백화점", companySize: "대기업·계열사·자회사", yearsEstablished: 24, location: "서울", startingSalary: 3120, ojakgyoRank: "C", graduateEmployment: 12 },
  { companyName: "지에스리테일", companySize: "대기업·계열사·자회사", yearsEstablished: 55, location: "서울", startingSalary: 2702, ojakgyoRank: "B", graduateEmployment: 12 },
  { companyName: "농협은행", companySize: "대기업·계열사·자회사", yearsEstablished: 14, location: "서울", startingSalary: 3976, ojakgyoRank: "C", graduateEmployment: 11 },
  { companyName: "우리은행", companySize: "대기업·계열사·자회사", yearsEstablished: 115, location: "서울", startingSalary: 4018, ojakgyoRank: "B", graduateEmployment: 10 },
  { companyName: "대한항공", companySize: "대기업·계열사·자회사", yearsEstablished: 57, location: "서울", startingSalary: 3768, ojakgyoRank: "B", graduateEmployment: 9 },
  { companyName: "현대건설", companySize: "대기업·계열사·자회사", yearsEstablished: 76, location: "서울", startingSalary: 2527, ojakgyoRank: "B", graduateEmployment: 7 },
  { companyName: "신한은행", companySize: "대기업·계열사·자회사", yearsEstablished: 129, location: "서울", startingSalary: 4058, ojakgyoRank: "C", graduateEmployment: 6 },
  { companyName: "한국조선해양", companySize: "대기업·계열사·자회사", yearsEstablished: 53, location: "서울", startingSalary: 3960, ojakgyoRank: "C", graduateEmployment: 6 },
  { companyName: "엘지디스플레이", companySize: "대기업·계열사·자회사", yearsEstablished: 41, location: "서울", startingSalary: 3931, ojakgyoRank: "C", graduateEmployment: 6 },
  { companyName: "효성", companySize: "대기업·계열사·자회사", yearsEstablished: 69, location: "서울", startingSalary: 3700, ojakgyoRank: "C", graduateEmployment: 6 },
  { companyName: "에스씨케이컴퍼니", companySize: "대기업·계열사·자회사", yearsEstablished: 29, location: "서울", startingSalary: 1818, ojakgyoRank: "C", graduateEmployment: 6 },
  { companyName: "삼성생명보험", companySize: "대기업·계열사·자회사", yearsEstablished: 69, location: "서울", startingSalary: 3986, ojakgyoRank: "C", graduateEmployment: 5 },
  { companyName: "효성인포메이션시스템", companySize: "대기업·계열사·자회사", yearsEstablished: 41, location: "서울", startingSalary: 3960, ojakgyoRank: "C", graduateEmployment: 5 },
  { companyName: "현대오토에버", companySize: "대기업·계열사·자회사", yearsEstablished: 26, location: "서울", startingSalary: 3953, ojakgyoRank: "A", graduateEmployment: 5 },
  { companyName: "에스케이쉴더스", companySize: "대기업·계열사·자회사", yearsEstablished: 26, location: "경기", startingSalary: 2949, ojakgyoRank: "C", graduateEmployment: 5 },
  { companyName: "씨제이푸드빌", companySize: "대기업·계열사·자회사", yearsEstablished: 26, location: "서울", startingSalary: null, ojakgyoRank: "C", graduateEmployment: 5 },
  { companyName: "조선호텔앤리조트", companySize: "대기업·계열사·자회사", yearsEstablished: 59, location: "서울", startingSalary: null, ojakgyoRank: "C", graduateEmployment: 5 },
  { companyName: "기아", companySize: "대기업·계열사·자회사", yearsEstablished: 82, location: "서울", startingSalary: 5614, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "에스케이하이닉스", companySize: "대기업·계열사·자회사", yearsEstablished: 77, location: "경기", startingSalary: 4058, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "중소기업은행", companySize: "공공기관", yearsEstablished: 65, location: "서울", startingSalary: 4018, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "현대엔지니어링", companySize: "대기업·계열사·자회사", yearsEstablished: 25, location: "서울", startingSalary: 4004, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "씨제이올리브네트웍스", companySize: "대기업·계열사·자회사", yearsEstablished: 31, location: "서울", startingSalary: 3924, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "한섬", companySize: "대기업·계열사·자회사", yearsEstablished: 39, location: "서울", startingSalary: 3466, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "디앤오", companySize: "대기업·계열사·자회사", yearsEstablished: 24, location: "서울", startingSalary: 3342, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "호텔신라", companySize: "대기업·계열사·자회사", yearsEstablished: 53, location: "서울", startingSalary: 3000, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "현대그린푸드", companySize: "대기업·계열사·자회사", yearsEstablished: 57, location: "경기", startingSalary: 2475, ojakgyoRank: "C", graduateEmployment: 4 },
  { companyName: "케이씨씨건설", companySize: "대기업·계열사·자회사", yearsEstablished: 37, location: "서울", startingSalary: 5211, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "대우조선해양", companySize: "대기업·계열사·자회사", yearsEstablished: 26, location: "경남", startingSalary: 4711, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "케이티", companySize: "대기업·계열사·자회사", yearsEstablished: 29, location: "경기", startingSalary: 4018, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "삼성디스플레이", companySize: "대기업·계열사·자회사", yearsEstablished: 14, location: "경기", startingSalary: 4018, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "포스코홀딩스", companySize: "대기업·계열사·자회사", yearsEstablished: 58, location: "경북", startingSalary: 3960, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "코오롱글로벌", companySize: "대기업·계열사·자회사", yearsEstablished: 66, location: "경기", startingSalary: 3953, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "에스케이브로드밴드", companySize: "대기업·계열사·자회사", yearsEstablished: 29, location: "서울", startingSalary: 3953, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "지에스건설", companySize: "대기업·계열사·자회사", yearsEstablished: 57, location: "서울", startingSalary: 3953, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "네이버", companySize: "중견기업", yearsEstablished: 27, location: "경기", startingSalary: 3947, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "농협정보시스템", companySize: "대기업·계열사·자회사", yearsEstablished: 20, location: "서울", startingSalary: 3921, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "엘지유플러스", companySize: "대기업·계열사·자회사", yearsEstablished: 30, location: "서울", startingSalary: 3894, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "케이티디에스", companySize: "대기업·계열사·자회사", yearsEstablished: 18, location: "서울", startingSalary: 3865, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "케이씨씨", companySize: "대기업·계열사·자회사", yearsEstablished: 68, location: "서울", startingSalary: 3779, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "현대카드", companySize: "대기업·계열사·자회사", yearsEstablished: 42, location: "서울", startingSalary: 3428, ojakgyoRank: "B", graduateEmployment: 3 },
  { companyName: "진에어", companySize: "대기업·계열사·자회사", yearsEstablished: 18, location: "서울", startingSalary: 3233, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "아시아나 항공", companySize: "대기업·계열사·자회사", yearsEstablished: 38, location: "서울", startingSalary: 3041, ojakgyoRank: "C", graduateEmployment: 3 },
  { companyName: "디비손해보험", companySize: "대기업·계열사·자회사", yearsEstablished: 58, location: "서울", startingSalary: 5000, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "두산중공업", companySize: "대기업·계열사·자회사", yearsEstablished: 64, location: "경남", startingSalary: 4851, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "에스원", companySize: "대기업·계열사·자회사", yearsEstablished: 49, location: "서울", startingSalary: 4401, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "아시아나아이디티", companySize: "대기업·계열사·자회사", yearsEstablished: 35, location: "서울", startingSalary: 4247, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "하나은행", companySize: "대기업·계열사·자회사", yearsEstablished: 36, location: "서울", startingSalary: 4204, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "엘지씨엔에스", companySize: "대기업·계열사·자회사", yearsEstablished: 39, location: "서울", startingSalary: 4066, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "현대모비스", companySize: "대기업·계열사·자회사", yearsEstablished: 49, location: "서울", startingSalary: 4018, ojakgyoRank: "B", graduateEmployment: 2 },
  { companyName: "현대트랜시스", companySize: "대기업·계열사·자회사", yearsEstablished: 27, location: "충남", startingSalary: 4012, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "삼성에스디아이", companySize: "대기업·계열사·자회사", yearsEstablished: 56, location: "경기", startingSalary: 3998, ojakgyoRank: "B", graduateEmployment: 2 },
  { companyName: "한국투자증권", companySize: "중소기업", yearsEstablished: 52, location: "서울", startingSalary: 3953, ojakgyoRank: "B", graduateEmployment: 2 },
  { companyName: "KB국민카드", companySize: "중소기업", yearsEstablished: 15, location: "서울", startingSalary: 3953, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "미래에셋증권", companySize: "대기업·계열사·자회사", yearsEstablished: 56, location: "서울", startingSalary: 3953, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "한화", companySize: "대기업·계열사·자회사", yearsEstablished: 74, location: "서울", startingSalary: 3929, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "카카오", companySize: "대기업·계열사·자회사", yearsEstablished: 31, location: "제주", startingSalary: 3754, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "한국푸르덴셜생명보험", companySize: "대기업·계열사·자회사", yearsEstablished: 37, location: "서울", startingSalary: 3727, ojakgyoRank: "B", graduateEmployment: 2 },
  { companyName: "넷마블", companySize: "대기업·계열사·자회사", yearsEstablished: null, location: "서울", startingSalary: 3615, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "디비하이텍", companySize: "중견기업", yearsEstablished: 73, location: "경기", startingSalary: 3610, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "롯데손해보험", companySize: "중소기업", yearsEstablished: 80, location: "서울", startingSalary: 3601, ojakgyoRank: "C", graduateEmployment: 2 },
  { companyName: "씨제이제일제당", companySize: "대기업·계열사·자회사", yearsEstablished: 19, location: "서울", startingSalary: 3485, ojakgyoRank: "B", graduateEmployment: 2 }
];